index:
  path: /
  controller: App\Controller\BlogController::index

noticia:
  path: /noticia/{id}
  controller: App\Controller\BlogController::noticia
  requirements:
    id: '\d+'

nuevaNoticia:
    path: /noticia/nueva
    controller: App\Controller\BlogController::nuevaNoticia

noticiaCreada:
    path: /noticia/creada
    controller: App\Controller\BlogController::noticiaCreada

editarNoticia:
    path: /noticia/editar/{id}
    controller: App\Controller\BlogController::editarNoticia
    requirements:
      id: '\d+'

borrarNoticia:
    path: /noticia/borrar/{id}
    controller: App\Controller\BlogController::borrarNoticia
